#!/usr/bin/env node
/**
 * Builds _test/harness.html — a copy of launch.html with _test/stubs.js injected
 * just after the Supabase CDN tag, so the real app code runs against fake
 * speech, API and auth layers and the whole onboarding flow can be driven
 * deterministically.
 *
 * Run: node _test/build-harness.js
 * Then open /_test/harness.html on the dev server and drive it via window.__T.
 *
 * The harness is generated, never hand-edited, and gitignored. Rebuild it after
 * any change to launch.html.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(ROOT, 'launch.html'), 'utf8');
const stubs = fs.readFileSync(path.join(__dirname, 'stubs.js'), 'utf8');

const anchor = '</script>';
const cdnTag = src.indexOf('supabase.min.js');
if (cdnTag === -1) {
  console.error('Could not find the Supabase CDN tag in launch.html — has the head changed?');
  process.exit(1);
}
const insertAt = src.indexOf(anchor, cdnTag) + anchor.length;

const out = src.slice(0, insertAt)
  + '\n<!-- TEST HARNESS — generated by _test/build-harness.js, do not edit -->\n<script>\n'
  + stubs
  + '\n</script>\n'
  + src.slice(insertAt);

const dest = path.join(__dirname, 'harness.html');
fs.writeFileSync(dest, out, 'utf8');
console.log('Wrote ' + path.relative(ROOT, dest) + ' (' + out.length + ' bytes)');
console.log('Open http://localhost:4321/_test/harness.html and drive it with window.__T');
